### ISSUE TITLE
It does not work with Lua, HTML, XML & Markdown files.

### ISSUE THREAD

**Issue by tomasorti** [zk-phi/sublimity#23]
I got the package from ELPA, version: sublimity-20150220.634:
I've tried with success in Elisp, shell scripting, C, C++, Python, JS, Ruby,  Processing... 
But the sublimity map does not appear with Lua, HTML, XML & Markdown files.
There might be more, but those are the ones I tested.

Is there a way to make it work with them?

**Comment by zk-phi** [comment]
Does it happens also on the vanilla Emacs ?
And please show me your sublimity settings if you have any.

**Comment by tomasorti** [comment]
Hi.
As long as I know, I am currently using vanilla Emacs on Linux and Mac OS X.
(No ErgoEmacs, no Aquamacs, just GNU Emacs in windows mode, not -nw) . 

The only thing regarding sublimity on my `init.el` is:
    (require 'sublimity)
    (sublimity-mode 1)
    (sublimity-map)

**Comment by zk-phi** [comment]
hmm... I couldn't reproduce on my vanilla Emacs (24.3 on Windows).

![untitled](https://cloud.githubusercontent.com/assets/3530521/7024122/80595312-dd75-11e4-926e-4f714f2acd45.png)

can you try running with `emacs -q` and `M-x eval-expression (require 'sublimity)` then `M-x sublimity -map` ?

**Comment by tomasorti** [comment]
Hi.
The languages that I tried where it is NOT working are: Lua, HTML, XML &
Markdown files.

For C/C++ works fine for me too, like in your C-mode screenshot.
The same for Elisp, shell scripting, C, C++, Python, JS, Ruby and
Processing.
In those it works well.

Regards,
Tom.

**Comment by zk-phi** [comment]
Thanks.

`sublimity-map` by default enabled only on modes that derives `prog-mode`. Though this behavior can be customized via setting `sublimity-map-criteria`, it seems reasonable to enable minimap in `text-mode` derived modes such as `markdown-mode`. I'll update the default value for the option later.

Anyway it's strange that `sublimity-map` is disabled in HTML, Lua, etc. buffers. I found that `web-mode` does not properly derive `prog-mode` (that is, `(derived-mode-p 'prog-mode)` does not return non-nil, unlike `html-mode`) so I suppose you are using `web-mode` for HTML buffers. Probably `lua-mode` also does not derive `prog-mode` (I'll look into later).
Since [https://www.gnu.org/software/emacs/manual/html_node/elisp/Basic-Major-Modes.html](the Emacs Lisp Manual) suggests major-mode authors to make new modes derive one of the basic major-modes (`prog-mode`, `text-mode`, `special-mode`), I think it's not a bug of `sublimity-map` but of `web-mode`, `lua-mode`, etc.
